package de.joonko.loan.offer.api.model;

public enum OfferResponseState {

    OFFERS_READY,
    FETCHING_USER_DATA,
    FETCHING_ADDITIONAL_INFORMATION,
    FETCHING_TRANSACTIONAL_DATA,
    FETCHING_OFFERS,
    MISSING_SALARY_ACCOUNT,
    BONIFY_USER_WITH_OUTDATED_SALARY_ACCOUNT,
    MISSING_PERSONAL_DATA,
    CLASSIFYING_TRANSACTIONS,
    WAITING,
    ERROR
}
