package de.joonko.loan.offer.domain;

public enum PreCheckEnum {

    ACCEPTED_USER_AGE,
    ACCEPTED_INCOME,
    ACCEPTED_3M_AVERAGE_INCOME,
    ACCEPTED_LATEST_SALARY,
    ACCEPTED_HAS_SALARY,
    ACCEPTED_NOT_JOINTLY_ACCOUNT,
    ACCEPTED_3_INCOME_TAGS,
    ACCEPTED_NO_GOV_SUPPORT,
    ACCEPTED_EMPLOYED_SINCE,
    ACCEPTED_EMPLOYMENT_TYPE,
    ACCEPTED_LOAN_AMOUNT,
    ACCEPTED_GAMBLING,
    ACCEPTED_CASH_WITHDRAWAL,
    ACCEPTED_TRANSACTIONS_ENCASHMENT,
    ACCEPTED_TRANSACTIONS_SEIZURE,
    ACCEPTED_TRANSACTIONS_P_ACCOUNT,
    ACCEPTED_TRANSACTIONS_CHARGEBACK,
    ACCEPTED_DELAY_IN_INSTALLMENTS,
    ACCEPTED_BONIMA_SCORE,
    ACCEPTED_LOAN_PURPOSE,

    ACCEPTED_UNLIMITED_CONTRACT,
    @Deprecated
    ACCEPTED_NO_PREVENTION_TAGS
}
