{{- if .Values.cronJobOfferStatus.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "loan.fullname" . }}-cronjob-offer-status
  namespace: {{ include "loan.fullname" . }}
spec:
  schedule: "0 9,15,21 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: curlimages/curl:latest
              env:
                - name: SYNC_USERNAME
                  value: bnfsuperadmin
                - name: SYNC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "loan.fullname" . }}
                      key: SECURITY_BASIC_ADMIN_PASSWORD
              args:
                - /bin/sh
                - -ec
                - |
                  curl http://{{ include "loan.serviceURL" . }}/admin/v1/sync/offer/status -u "${SYNC_USERNAME}:${SYNC_PASSWORD}" -H 'Content-Type: application/json' --data-raw '{ "banks":["SANTANDER"]}'
          restartPolicy: OnFailure
{{- end }}

