{{- if .Values.cronJobFtsDeletion.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "loan.fullname" . }}-cronjob-fts-deletion
  namespace: {{ include "loan.fullname" . }}
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: curlimages/curl:latest
              env:
                - name: SYNC_USERNAME
                  value: bnfsuperadmin
                - name: SYNC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "loan.fullname" . }}
                      key: SECURITY_BASIC_ADMIN_PASSWORD
              args:
                - /bin/sh
                - -ec
                - |
                  curl -X DELETE http://{{ include "loan.serviceURL" . }}/admin/v1/user/fts -u "${SYNC_USERNAME}:${SYNC_PASSWORD}" -H 'Content-Type: application/json'
          restartPolicy: OnFailure
  {{- end }}

