package de.joonko.loan.db.vo;

public enum LoanApplicationAuditTrailStatus {

    LOAN_DEMAND_REQUEST_RECEIVED,
    LOAN_DEMAND_DAC_OVERVIEW,
    LOAN_DEMAND_REQUEST_SENT,
    LOAN_DEMAND_RESPONSE_RECEIVED_SUCCESS,
    LOAN_DEMAND_RESPONSE_RECEIVED_ERROR,
    LOAN_DEMAND_RESPONSE_RECEIVED_AS_RED_PROFILE,
    LOAN_DEMAND_RESPONSE_RECEIVED_AS_YELLOW_PROFILE,
    LOAN_DEMAND_RESPONSE_RECEIVED_AS_GREEN_PROFILE,
    LOAN_DEMAND_RESPONSE_RECEIVED,
    LOAN_DEMAND_REQUEST_SERVED,
    ACCEPT_OFFER_REQUEST_RECEIVED,
    ACCEPT_OFFER_BY_INTERNAL_USER_REQUEST_RECEIVED,
    ACCEPT_OFFER_REQUEST_SENT,
    ACCEPT_OFFER_RESPONSE_RECEIVED_SUCCESS,
    ACCEPT_OFFER_REQUEST_SERVED_SUCCESS,
    ACCEPT_OFFER_REQUEST_SERVED_ERROR,
    ACCEPT_OFFER_RESPONSE_RECEIVED_ERROR,
    DAC_EMAIL_NOTIFICATION_SUCCESS,
    DAC_EMAIL_NOTIFICATION_ERROR,
    KYC_LINK_CREATED,
    ERROR,
    REMARK;


}


