### Get Token

POST  {{host}}api/v1/joonkocfgesign/login
Content-Type: application/json

{
  "apiKey": "X277HCOPNGKL97898ANBWEKJ7TCOTGE9U2HIURDM"
}

> {%
    client.global.set("X-API-LOGIN-TOKEN", response.body.authToken);
%}

###
POST  {{host}}/api/v1/joonkocfgesign/identifications/test3/start
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

{
  "birthday": "1987-05-23",
  "birthplace": "London",
  "city": "London",
  "country": "GB",
  "custom1": "X-MANUALTEST-ABORTIDENT",
  "custom2": "Custom fields",
  "custom3": "can set testbot scenarios",
  "custom4": "or store any data strings",
  "custom5": "you like.",
  "email": "hello@fdgdgdg.org",
  "firstname": "Olivia",
  "gender": "FEMALE",
  "lastname": "Jones",
  "mobilephone": "01789012345",
  "nationality": "GB",
  "street": "Baker Street",
  "zipcode": "W1U"
}


### Start Web based identification-- need web browser , using transaction number
GET https://go.test.idnow.de/joonkocfgesign/identifications/test3
Content-Type: application/json

### Start Web based identification-- need web browser , using IDnet Id
https://go.test.idnow.de/TST-ZYQEE
GET https://go.test.idnow.de/joonko/identifications/niraj-sonawane1
Content-Type: application/json


### Get IDent
GET  {{host}}/api/v1/joonkocfgesign/identifications
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

###
### Get IDent with status
GET  {{host}}/api/v1/joonkocfgesign/identifications?aborted=true
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

###


###
### Get singed contractResponse
GET  {{host}}/api/v1/joonkocfgesign/identifications/7b15049a-983a-4241-b204-33c459d9651c/documents/contractResponse/signed
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

### Get document definations

GET  {{host}}/api/v1/joonkocfgesign/documentdefinitions/contract
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

### Get All document definations

GET  {{host}}/api/v1/joonkocfgesign/documentdefinitions
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

###
### Delete document definations

DELETE  {{host}}/api/v1/joonkocfgesign/documentdefinitions/acknowledgment
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

### Create document defination

POST {{host}}/api/v1/joonkocfgesign/documentdefinitions
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

{
  "optional": false,
  "name": "contract",
  "identifier": "contract",
  "mimeType": "application/pdf",
  "sortOrder": 1
}

###
####/api/v1/company-xyz/documentdefinitions/doc1/data

POST {{host}}/api/v1/joonkocfgesign/documentdefinitions
Content-Type: application/json
X-API-LOGIN-TOKEN:  {{X-API-LOGIN-TOKEN}}

{
  "optional": true,
  "name": "acknowledgment",
  "identifier": "acknowledgment",
  "mimeType": "application/pdf",
  "sortOrder": 1
}

### Uplaod default document
curl -i -X POST --data-binary @localfile.pdf --header "X-API-LOGIN-TOKEN:asdgg38434-34guzf3f4zf34fz34-ugfgu3u34" --header "ContentType:application/octet-stream" http://gateway.test.idnow.de/api/v1/joonkocfgesign/documentdefinitions/acknowledgment/data

###
Step 1 : create document defincation for acknowledgment using curl/postman for joonkocfgesign
Step 2 : upload defaut document using curl command
Step 3 : Test identification on joonko stg and verify the acknowledgment document is visible
Step 4 : run step 1 and step 2 for production

###

